export const estados = [
    {value: "Aguascalientes"},
    {value: "Baja California"},
    {value: "California Sur"},
    {value: "Campeche"},
    {value: "Chiapas"},
    {value: "Chihuahua"},
    {value: "Coahuila"},
    {value: "Colima"},
    {value: "Distrito Federal"},
    {value: "Durango"},
    {value: "Guanajuato"},
    {value: "Guerrero"},
    {value: "Hidalgo"},
    {value: "Jalisco"},
    {value: "México"},
    {value: "Michoacán"},
    {value: "Morelos"},
    {value: "Nayarit"},
    {value: "Nuevo León"},
    {value: "Oaxaca"},
    {value: "Puebla"},
    {value: "Querétaro"},
    {value: "Quintana Roo"},
    {value: "Luis Potosí"},
    {value: "Sinaloa"},
    {value: "Sonora"},
    {value: "Tabasco"},
    {value: "Tamaulipas"},
    {value: "Tlaxcala"},
    {value: "Veracruz"},
    {value: "Yucatán"},
    {value: "Zacatecas"}
]

export const microsegmentos = [
    {value: "INDIGENISTAS"},
    {value: "PET FRIENDLY"},
    {value: "AMBIENTALISTAS"},
    {value: "MILLENIALS"},
    {value: "DERECHOS HUMANOS"},
    {value: "ESTUDIANTES"},
    {value: "ARTISTAS"},
    {value: "AGRICULTORES"},
    {value: "DEPORTE"},
    {value: "MADRES"},
    {value: "LGTB"},
    {value: "RELIGIOSOS"},
    {value: "CICLISTAS"},
    {value: "DISCAPACITADOS"},
    {value: "EMPRESARIOS"},
    {value: "3a EDAD"},
    {value: "GEEKS"},
    {value: "VENDEDORES"},
    {value: "MÉDICOS"},
    {value: "PROFESORES"},
    {value: "FEMINISTAS"},
    {value: "OTROS"}
]